### ISSUE TITLE
climpred would like to use doppyo metrics

### ISSUE THREAD

**Issue by aaronspring** [csiro-dcfp/doppyo#1]
The metrics you implemented in `doppyo` are awesome. we would really like to integrate them into `climpred`.

Tried `climpred` and `doppyo` metrics here: https://gist.github.com/aaronspring/eef9496aad6516e6afcf3a89db35b0c9 and our issue https://github.com/bradyrx/climpred/issues/382
We can easily integrate `reliability`, `rank_histogram`, `contingency` and all depending.

Would you be ok with a PR moving the install requirements for `bokeh`, `pyspharm` and `windspharm` as extra? https://stackoverflow.com/questions/10572603/specifying-optional-dependencies-in-pypi-python-setup-py
These mostly used for the diagnostics which are not strictly needed for the forecast verification part.

Also our data model works with xr.Datasets only, whereas you require xr.DataArrays. This we could wrap. 

Another solution, if you want to keep `doppyo` as is, would be to transfer the code of the metrics into `xskillscore` https://github.com/raybellwaves/xskillscore/? This repo hosts already probabilistic and deterministic verification metrics.

@bradyrx @jmunroe @Thomas-Moore-Creative

**Comment by dougiesquire** [comment]
All of `doppyo`'s skill metrics are being ported to `xskillscore` (https://github.com/raybellwaves/xskillscore)
